micronaut:
  application:
    name: Fandango

mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
  database: ${MONGO_DATABASE:fandango}
  imageCollection: ${MONGO_COLLECTION:images}
  thumbnailCollection: ${MONGO_COLLECTION:thumbnails}
  fileCollection: ${MONGO_COLLECTION:files}


image:
  thumbnailSize: 300

jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  serializationInclusion: always
  deserialization:
failOnUnknownProperties: false